version: '3'

services:
  app:
    image: node:18-bullseye-slim
    container_name: svelte-view-translation
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    ports:
      - 3000:3000